name: "NorthStar"
version: "0.1.0"
config-version: 2

profile: "NorthStar"

vars:
  bronze_dir: "../data/bronze"


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  NorthStar:
    staging:
      +materialized: view



